### ISSUE TITLE
Tabs stopped working

### ISSUE THREAD

**Issue by IreAy0** [cdmoro/bootstrap-vue-3#485]
The btabs and btab is not working..

Help

**Comment by VividLemon** [comment]
I believe whatever issue you are facing is fixed in an unreleased version

**Comment by hff135** [comment]
I'm having this problem too.

**Comment by sanjayosx** [comment]
I am facing the same issue. I downgraded to 0.1.13 but still not working.

**Comment by MrTanoshii** [comment]
It was fixed in https://github.com/cdmoro/bootstrap-vue-3/pull/447 which is available in `0.1.15` onwards (not available via npm currently). 

The options are to:
1. Revert to a previous version
2. Use latest from GitHub
3. Leave it in its broken state until the new npm release https://github.com/cdmoro/bootstrap-vue-3/issues/467

**Comment by mariusa** [comment]
Working in current release
